### ISSUE TITLE
Got error when running the lucid.py 

### ISSUE THREAD

**Issue by Nishan-Charlie** [risingfbk/p4ddle#2]
File "/home/nishan/Desktop/Sangee/p4 Machine/p4ddle/p4-ddos/p4ddle/control-plane/lucid_cnn.py", line 28, in <module>
    import p4_util
  File "/home/nishan/Desktop/Sangee/p4 Machine/p4ddle/p4-ddos/p4ddle/control-plane/p4_util.py", line 5, in <module>
    import bmpy_utils as utils
ModuleNotFoundError: No module named 'bmpy_utils'

**Comment by Nishan-Charlie** [comment]
I already build the BMV2 But Still the issue not gone

**Comment by luisdknob** [comment]
Hi Nishan,

You need to check in which folder the BMv2 installed the libs. 

In my machine was installed in the folder /usr/local/lib/python3.9/site-packages.

You can check that with the command sudo find /usr/lib -name bmpy_utils*

After, update line 2 in the file p4_util.py with the correct folder.

**Comment by Nishan-Charlie** [comment]
Thanks for the help It works now but I couldn't download the dataset.
The dataset I got from kaggle is in different format. If you can send it to my email it will be great thanks in advance.
NishanNishankar@gmail.com

Can u please guide me to run this projects.

**Comment by Nishan-Charlie** [comment]
![image](https://github.com/risingfbk/p4ddle/assets/66866762/3dd5e269-9144-42ed-b90b-30a20943c788)

**Comment by luisdknob** [comment]
Hello Nishan,

Unfortunately, we are not the dataset owners, so I can not make it available. Your best option is to enter in contact with the UNB and ask it directly to them.

In the original LUCID repo (https://github.com/doriguzzi/lucid-ddos/), you can find a small set of pcaps and a how-to about creating/training the model.

After that, you can try running the validation pcap with the tcpreplay on p4ddle.
