### ISSUE TITLE
python 3.10, tensorflow 2.8.4 with numpy version compatibility issue

### ISSUE THREAD

**Issue by Jenny176** [risingfbk/p4ddle#6]
I'm sorry for creating this issue, I would like to ask, I have configured it according to your environment but when I run lucid_cnn.py, python 3.10 requires numpy>=2.0, tensorflow 2.8.4 requires numpy1.x,how should this conflict be resolved?

**Comment by luisdknob** [comment]
Hi, 

Tensorflow constantly removes versions from the pip repo and creates this incompatibility. I will reinstall it during the week and update the code and repo, if necessary, to new versions of numpy and tensorflow.

**Comment by luisdknob** [comment]
I updated the code to tensorflow==2.13.0. Now, I imagine that you will not have any problems with numpy 2.

**Comment by Jenny176** [comment]
> 我将代码更新为 tensorflow==2.13.0。现在，我想您在使用 numpy 2 时不会遇到任何问题。

Really appreciate your answer and helping me out! wish you the best of luck!

**Comment by luisdknob** [comment]
I will close the issue. If you want, you can reopen it.
